### ISSUE TITLE
DOS with GLLBsc

### ISSUE THREAD

**Issue by sergbuto** [shankar1729/jdftx#184]
I have calculated the charge density using the GLLBs potential. Now , when I try to calculate DOS using the 'fix-electron-density' command in the input file, it says 'Potential functionals do not support total-energy minimization; use SCF instead.' Is there any way  to get DOS using already calculated ElecDensity or I have to re-do the whole calculation using SCF?

Another question regarding potentials:
I read that AK13 is used with no correlation added, however, the 'elec-ex-corr' command requires to put in something for 'funcC'. Is there any way around that?

**Comment by shankar1729** [comment]
Thanks for pointing this out: I pushed two commits to address these:

1. Fixed an unnecessary check that was preventing this already supported functionality to do non-self-consistent orbital-dependent functionals. Note that you must dump Vscloc and used fix-electron-potential (not fix-electron-density).
2. I added options to specify x-none and c-none if you want to run without exchange and/or correlation.

**Comment by shankar1729** [comment]
Please run printStackTrace on that jdftx-stacktrace and report the processed output (those hex codes are specific to your build, so need to run this on the system/build where you encountered this issue).

**Comment by shankar1729** [comment]
Just run `/path-to-jdftx/scripts/printStackTrace jdftx-stacktrace` in the directory where you ran and got this error. (There will be a file jdftx-stacktrace in that directory.)

**Comment by sergbuto** [comment]
Still have a problem with some MGGAs from libxc.

Here is the printStackTrace output after using mgga-x-tb09 with mgga-c-tpss

printStack(bool) at ??:?
stackTraceExit(int) at ??:?
matrix::diagonalize(matrix&, diagMatrix&) const at ??:?
ElecVars::applyHamiltonian(int, diagMatrix const&, ColumnBundle&, Energies&, bool) at ??:?
BandDavidson::minimize() at ??:?
bandMinimize(Everything&, bool) at ??:?
SCF::cycle(double, std::vector<double, std::allocator<double> >&) at ??:?
Pulay<SCFvariable>::minimize(double, std::vector<std::__cxx11::basic_string<char, ichar_traits, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, ichar_traits, std::allocator<char> > > >, std::vector<double, std::allocator<double> >) at ??:?
SCF::minimize() at ??:?
elecMinimize(Everything&) at ??:?
elecFluidMinimize(Everything&) at ??:?
IonicMinimizer::compute(IonicGradient*, IonicGradient*) [clone .localalias.457] at IonicMinimizer.cpp:?
Minimizable<IonicGradient>::lBFGS(MinimizeParams const&) at ??:?
Minimizable<IonicGradient>::minimize(MinimizeParams const&) at ??:?
IonicMinimizer::minimize(MinimizeParams const&) at ??:?
main at ??:?
_start at ??:?

Here is the output after using mgga-x-scan and mgga-c-scan:

printStack(bool) at ??:?
stackTraceExit(int) at ??:?
FunctionalLibXC::evaluate(int, int, double const*, double const*, double const*, double const*, double*, double*, double*, double*, double*) const at ??:?
void threadLaunch<void (int, int, FunctionalLibXC const*, int, int, double const*, double const*, double const*, double const*, double*, double*, double*, double*, double*), FunctionalLibXC const*, int, int, double const*, double const*, double const*, double const*, double*, double*, double*, double*, double*>(int, void (*)(int, int, FunctionalLibXC const*, int, int, double const*, double const*, double const*, double const*, double*, double*, double*, double*, double*), unsigned long, FunctionalLibXC const*, int, int, double const*, double const*, double const*, double const*, double*, double*, double*, double*, double*) at ??:?
ExCorr::operator()(std::vector<std::shared_ptr<ScalarFieldData>, std::allocator<std::shared_ptr<ScalarFieldData> > > const&, std::vector<std::shared_ptr<ScalarFieldData>, std::allocator<std::shared_ptr<ScalarFieldData> > >*, IncludeTXC, std::vector<std::shared_ptr<ScalarFieldData>, std::allocator<std::shared_ptr<ScalarFieldData> > > const*, std::vector<std::shared_ptr<ScalarFieldData>, std::allocator<std::shared_ptr<ScalarFieldData> > >*, matrix3<double>*) const at ??:?
ElecVars::EdensityAndVscloc(Energies&, ExCorr const*) at ??:?
ElecVars::elecEnergyAndGrad(Energies&, ElecGradient*, ElecGradient*, bool) at ??:?
SCF::minimize() at ??:?
elecMinimize(Everything&) at ??:?
elecFluidMinimize(Everything&) at ??:?
IonicMinimizer::compute(IonicGradient*, IonicGradient*) [clone .localalias.457] at IonicMinimizer.cpp:?
Minimizable<IonicGradient>::lBFGS(MinimizeParams const&) at ??:?
Minimizable<IonicGradient>::minimize(MinimizeParams const&) at ??:?
IonicMinimizer::minimize(MinimizeParams const&) at ??:?
main at ??:?
_start at ??:?

**Comment by sergbuto** [comment]
For test purposes, I did calculations for MAPbBr3 using the GLLBsc functional with SG15 PBE pseudos. The obtained bandgap value (without SOC included) was 2.34 eV while in publication by Castelli et al. APL Mater. 2, 081514 (2014) [https://doi.org/10.1063/1.4893495] the calculated bandgap is 2.88 eV. The difference of 0.54 eV is too large in my opinion to explain by the use of different pseudos and different optimization of the crystal structure.

In fact, a promising good performance of GLLBsc in terms of the band gap, as expected from the literature overview, was not impressive when used in JDFTx. According to my tests, a number of gga and mgga functionals were doing better in terms of the bandgap in calculations for MAPbBr3 with SOC. 

Do you have an idea why that is? It is not easy to think of something done wrong on my side.

**Comment by shankar1729** [comment]
GLLBsc has an extra quasiparticle correction which is not a part of the KS eigenvalues. Use 'dump End OrbitalDep' to calculate this correction: it will generate an eigenvalsQP file. You can then use this eigenvalsQP file to calculate the density of states using the EigsOverride parameter in command density-of-states. Let me know if you encounter any issues in this; we don't particularly use GLLBsc very often as its accuracy in electronic structure, convergence and workflow are somewhat challenging.

**Comment by sergbuto** [comment]
Following this procedure has improved the size of the gap but still not to the extent one would like to have for calculations with SOC. The possibility to use correlation from libxc other than PBEsol with GLLBsc would be very valuable.

**Comment by shankar1729** [comment]
What was the gap you obtained using this procedure compared to the published result? We did find that potential-only functionals like GLLBsc was more sensitive to a number of computational parameters in contrast to conventional XC functionals that define an energy.

In the paper linked above, it does not appear that they do SOC calculations self-consistently with GLLBsc, but instead add SOC and exciton binding energy corrections ad hoc to the non-SOC GLLBsc results.

If you want to test GLLBsc with other correlation functionals, you can modify ExCorr.cpp at line 480. At the moment, we don't have a good reason to allow mixing internal and LibXC functionals, and hence this is not something you can do from the input yet.

**Comment by sergbuto** [comment]
In my last post I actually meant a comparison of the GLLBsc-calculated gap with one from experiment not from somebody-else's calculations. For MAPbBr3, the GLLBsc+SOC-calculated gap was 1.67 eV while it is around 2.3 eV in experiment.

I guess in ExCorr.cpp one can switch to only other internal correlation functional but those do not include the ones I would like to try.

**Comment by shankar1729** [comment]
Ah I see: what GLLBsc gap did you get without SOC? (Compared to the 2.88 eV they reported.) It could be that something about the GLLBsc definition does not play nice with SOC, and that may be why they didn't compute that self-consistently.

You should be able to replace that line in the code with something like `functionals->add(XC_MGGA_C_SCAN, "correlation");` See the xc.h from libXC for what codes to use. It's just that this sort of mixing is not supported by the command syntax in the input file (and not planned to for the moment).

**Comment by sergbuto** [comment]
Without SOC, KS (HOMO-LUMO) gap  is 2.38 eV, quasiparticle gap is 3.33 eV which is larger than reported 2.88 eV.
With SOC,  KS (HOMO-LUMO) gap  is 1.19 eV, quasiparticle gap is 1.67 eV.

As to changes to ExCorr.cpp, do you mean something like this:

			functionals->add(GGA_X_GLLBsc);
			orbitalDep = std::make_shared<ExCorr_OrbitalDep_GLLBsc>(*e);
			functionals->add(XC_GGA_C_PBE_SOL);

where XC_GGA_C_PBE_SOL is taken from xc_func.h of LIBXC?

**Comment by shankar1729** [comment]
Hmm, that seems like a large difference still. Did you converge the structure (including lattice) with PBEsol as that paper had done? The band gaps of hybrid perovskites are quite sensitive to the lattice constants and structures. Also, try comparing the results for an inorganic perovskite with less ionic degrees of freedom to make sure the structures are fully consistent.

And yes, that should be the appropriate code for mixing internal and LibXC functionals; of course this is not tested behavior, so let me know if that fails for some reason.

**Comment by sergbuto** [comment]
I tried this change to ExCorr.cpp.  It made the SCF convergence much worse even in the case of the PBESOL correlation from LIBXC.

**Comment by shankar1729** [comment]
That's strange: it shouldn't have made any difference whether the PBE-sol came from LibXC or internal. As a test, maybe you can try mixing internal and libxc functional for a better-behaved case eg. PBEsol i.e. try changing the line starting on 458 in ExCorr.cpp to:

```
case ExCorrGGA_PBEsol:
	functionals->add(GGA_X_PBEsol);
	functionals->add(XC_GGA_C_PBE_SOL, "correlation");
```

If you can confirm that mixing PBEsol that way works out well, then we can try to figure out why GLLBsc is misbehaving.

**Comment by sergbuto** [comment]
I did testing you ask for. 

First I did a run with "elec-ex-corr gga-PBEsol" and "elec-ex-corr gga-x-pbe-sol gga-c-pbe-sol". Both runs eneded with the same numbers of SCF-cycles and identical numbers (e.g dEtot), except for small difference in times. 

Then, I did the change in ExCorr.cpp:
         case ExCorrGGA_PBEsol:
	       functionals->add(GGA_X_PBEsol);
	       functionals->add(XC_GGA_C_PBE_SOL, "correlation");
and recompiled.

The run with "elec-e x-corr gga-PBEsol" did not show worse SCF convergence (the same number of SCF-cycles) but the numbers (e.g. dEtot) were significantly different.

**Comment by shankar1729** [comment]
Thanks: so that implies that the issue with GLLBsc you encountered may be an instability in the SCF of that, with slight numerical differences between internal and LibXC functionals diverging the results. You may want to check if the GLLBsc run with less aggressive SCF mixing parameters (say mixFraction ~ 0.1) performs better with the LibXC correlation.
